CREATE TABLE PATIO (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    cols INT NOT NULL,
    rows INT NOT NULL
);

CREATE TABLE SETOR (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    slots INT NOT NULL,
    patio_id BIGINT NOT NULL,
    FOREIGN KEY (patio_id) REFERENCES PATIO(id)
);